version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rpg-postgres
    environment:
      POSTGRES_DB: rpg_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: mantulin-rpg-hibernate-1:latest
    container_name: rpg-hibernate-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rpg_db
      DB_USER: postgres
      DB_PASS: postgres

volumes:
  pgdata:
